# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'rspec/collection_matchers'
require 'timeout'

require 'ezmq'
$:.unshift File.join(File.dirname(__FILE__), 'support')

Process.setrlimit(:NOFILE, 8192)    # Don't run out of file handles
Thread.abort_on_exception = true

# Log testing activity if there's a log directory
logdir = File.join(File.dirname(__FILE__), '..', 'log')
if Dir.exist?(logdir)
  require 'logger'
  EZMQ.logger = Logger.new File.join(logdir, 'spec.log'), 2, 2_000_000
  EZMQ.logger.level = Logger::DEBUG
end


RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Some specs are specific by 0mq version...
  case EZMQ.zmq_version
  when /^3\./
    config.filter_run_excluding version: 4
  when /^4\./
    config.filter_run_excluding version: 3
  end

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
  config.raise_errors_for_deprecations!

  config.around(:each) do |example|
    begin
      Timeout::timeout(10) do
        example.run
      end
    ensure
      EZMQ.terminate! unless EZMQ.context.closed?
    end
  end
end
